#!/bin/bash
docker stop test_postgres || true
docker run --rm \
	--name test_postgres \
	-p 5432:5432 \
	-e POSTGRES_USER=test\
	-e POSTGRES_PASSWORD=test\
	-e POSTGRES_DB=test_db\
	-d postgres:latest
