#!/bin/bash
CONTAINER_NAME=test_postgres

docker stop $CONTAINER_NAME || true
docker run --rm \
	--name $CONTAINER_NAME \
	-p 5432:5432 \
	-e POSTGRES_USER=test\
	-e POSTGRES_PASSWORD=test\
	-e POSTGRES_DB=test_db\
	-d postgres:latest
