#!/bin/bash
if [$# -eq 0]; then
    echo "No filename provided. main.py will used"
    $filename = "main.py"
else
    $filename = "$1"
fi

counter=1

while [ -e "$filename" ];do
    filename="${filename%.*}$counter.py"
    coutner=$((counter+1))
done

cat > "$filename" << EOF 
from datetime import datetime
from functools import wraps


def count_running_time(func):
    @wraps(func)
    def wrapper(*args, **kwargs):
        start_time = datetime.now()
        res = func(*args, **kwargs)
        end_time = datetime.now()
        print('Running time: ', end_time - start_time)
        return res
    return wrapper


def test():
    pass


def main():
    pass


if __name__ == '__main__':
    main()
EOF

echo "File '$filename' created"
